### ISSUE TITLE
VisuliseProgress.ipynb error

### ISSUE THREAD

**Issue by nbaron17** [PWhiddy/PokemonRedExperiments#182]
![image](https://github.com/user-attachments/assets/8358ba06-9988-4a3c-98fc-b070c0e1ff89)

Installed the requirements and ran the notebook only to get this error.

**Comment by PWhiddy** [comment]
Hi!
To run that notebook you need to change the grid size so that its a multiple of the number of environments you're running. 
However I will also say that the notebook is a bit outdated - the preferred method now is to use tensorboard/wandb + the map viz for tracking progress. 

hope that's helpful!

**Comment by nbaron17** [comment]
Thanks!
