### ISSUE TITLE
[reference] pokemon emerald ai

### ISSUE THREAD

**Issue by Tom-Neverwinter** [PWhiddy/PokemonRedExperiments#3]
https://www.youtube.com/watch?v=9YyQJIuN7n0

Thought I would reference this item. as it appears relevant

https://remptongames.com/2020/06/22/how-i-taught-an-ai-to-play-pokemon-emerald/

https://github.com/RemptonGames/PokemonEmeraldAI

more advanced reference: https://www.youtube.com/watch?v=rhvj7CmTRkg

**Comment by dukemagus** [comment]
Not the same approach: it reads a lot of data from the emulator memory, rather than processing the on-screen information and it already has plenty of game information tagged and identified in other files.

It's basically like giving a cheat sheet for the agent. Even if it still doesn't know what to do with that info, it'll skew the decision making process and it'll try to associate whatever happenes to the preset variables and memory coordinates it is reading.

**Comment by PWhiddy** [comment]
That was a cool project, big props to Rempton for his work on that and sharing the process. This version does also read some state from emulator memory too, but overall is a quite different approach.
