### ISSUE TITLE
how to start such a project ?

### ISSUE THREAD

**Issue by Tomin-Moreau** [PWhiddy/PokemonRedExperiments#68]
Hi,
I'm French (sorry bad English)  and I have a a school project to train autonomous model cars for real races . Here the link https://ajuton-ens.github.io/CourseVoituresAutonomesSaclay/

What i want to know is how to approach the task ? I'm planning to use gymnasium and stable-baselines3  for training. However, I find that you manage to show the progress of the IA really well, something I hope to achieve.

So the big questions : how many hours have you put in it ? From witch angle do you start the project ? 

Your project already inspired mine so I will start working to hopefully have a car that make a least one lap.
Thank you for your amazing work !

**Comment by PWhiddy** [comment]
Hi!
That's a very big project! It will be very challenging to do reinforcement learning directly on a real car because it requires a huge number trials, and would probably crash a ton during the process. 
One approach is to train first using a car simulator and then use that model as a starting point for the real car. 
One very cool approach which learns its own simulation of the environment is "dreamer": 

https://www.youtube.com/watch?v=xAXvfVTgqr0
https://github.com/danijar/dreamerv3

Overall, my advice would be to start as simple as possible, manually programming the car to follow the course, and gradually test out more sophisticated methods. Traditional approaches are very hard to beat in this area.

Hope that's helpful!

**Comment by Tomin-Moreau** [comment]
thanks !
we are using webots for the simulation so we have a platform to train our models so i think your approach and mine will be pretty similar. Anyway, thanks for the video, it was very insightful
