### ISSUE TITLE
Disable agent from being able to use start/B buttons

### ISSUE THREAD

**Issue by RussellMaggs** [PWhiddy/PokemonRedExperiments#82]
It makes sense in my mind that further restricting what actions an agent can take will allow for faster learning and mastery of what it can do
 
 I believe the start button will eventually be required to use HM but I believe that isn't required until Vermillion city?
 
  has anyone experimented round with this? When I finish my current experiment I am happy to give this a try and see what happens

**Comment by PWhiddy** [comment]
So this is kind of funny but it was actually just pointed out to me that there is a bug in my code that releases the start button, meaning that it effectively has been unusable this whole time. But I think this has actually helped it because otherwise it can pull up the menu anywhere to get extra exploration reward 😅. So I'd say the idea checks out. I'm not so sure disabling the B button is as helpful though.

**Comment by RussellMaggs** [comment]
Ah well in this case I think we can close this issue for now, if I ever decide to experiment with disabling the B button I will create a new discussion if the results are interesting

**Comment by PWhiddy** [comment]
Cool. Going to push an update soon that allows enabling/disabling start button in the config.
