### ISSUE TITLE
Having More than one session

### ISSUE THREAD

**Issue by SeiferVIII5** [PWhiddy/PokemonRedExperiments#96]
When I start python run_baseline_parallel.py
I always just does 1 game at a time, how do I start 10 or 20 at the same time?
Thank you

**Comment by techmore** [comment]
Interesting. The default setting in [run_baseline_parallel.py](https://github.com/PWhiddy/PokemonRedExperiments/blob/master/baselines/run_baseline_parallel.py) on line 43 is 
`num_cpu = 44 `

You can see here I added a line to make it 10 and to print the receive value using 
`print('num : ', num_cpu)`

just make sure that line is 44, or below the num_cpu = 44 declaration. Below are 2 screenshots with the modifications where you see 44 agents, and 10 agents. For my setup 64 runs best on an m1pro.

Let us know what issues you run into.

<img width="1342" alt="Screenshot 2023-10-21 at 1 14 03 PM" src="https://github.com/PWhiddy/PokemonRedExperiments/assets/9263712/391e53d6-969d-40af-9d67-e3d47ceef887">

<img width="1382" alt="Screenshot 2023-10-21 at 1 15 57 PM" src="https://github.com/PWhiddy/PokemonRedExperiments/assets/9263712/f18ca23a-dab5-437a-ab96-360bbd18c54a">

**Comment by lg4** [comment]
When you run a single instance of run_baseline_parallel.py, it will reference num_cpu within the file to choose the number of games. You can confirm this under your session folder, counting each screenshot it produces.

https://github.com/PWhiddy/PokemonRedExperiments/blob/fa01143e4b8d165136199be7155757495d16e56a/baselines/run_baseline_parallel.py#L43C4-L43C4

`num_cpu = 44 #64 #46  # Also sets the number of episodes per training iteration
    env = SubprocVecEnv([make_env(i, env_config) for i in range(num_cpu)])`

The value in the file is 44, but I imagine it would default to your max cpu count otherwise.
    
Alternatively, you could replace this value with `num_cpu = os.cpu_count()` and it will max out at your core count.

I see someone else responded earlier but I never hit 'Comment'! 

Good luck!

**Comment by PWhiddy** [comment]
Try out the new `run_baseline_parallel_fast.py` script, the default is 16 envs/cpus but you can try more of less!
